### ISSUE TITLE
Release 0.4.2 with publishPlugin?

### ISSUE THREAD

**Issue by olafurpg** [dancingrobot84/sbt-idea-plugin#7]
The latest release, 0.4.1, does not include the `publishPlugin` task. I would love to use it to automate the release of the [scalafmt](https://plugins.jetbrains.com/plugin/8236?pr=) intellij plugin.

cc/ https://github.com/olafurpg/scalafmt/issues/399

**Comment by nkly** [comment]
Sure, no problem :)
